services:
  app:
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
  python:
    image: "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - 7698:7698
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data
    restart: always
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333 # REST API
    restart: always
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data:
  redis-data:
  redisinsight:
